# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('AdId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='NA', max_length=64)),
                ('GRE', models.IntegerField(default=0)),
                ('GRE_W', models.FloatField(default=0)),
                ('GPA', models.FloatField(default=0)),
                ('TF', models.IntegerField(default=0)),
                ('TF_S', models.IntegerField(default=0)),
                ('major', models.CharField(default='NA', max_length=64)),
                ('college', models.CharField(default='NA', max_length=64)),
                ('exp', models.CharField(default='NA', max_length=128)),
                ('year', models.CharField(default='NA', max_length=64)),
                ('country', models.CharField(default='NA', max_length=16)),
                ('ap_date', models.DateField(default='2016-01-01')),
                ('result', models.CharField(default='NA', max_length=16)),
                ('adschool', models.CharField(default=' ', max_length=32)),
                ('degree', models.CharField(default='NA', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(default='NA', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('GRE', models.IntegerField(default=0)),
                ('GRE_W', models.FloatField(default=0)),
                ('GPA', models.FloatField(default=0)),
                ('TF', models.IntegerField(default=0)),
                ('TF_S', models.IntegerField(default=0)),
                ('major', models.CharField(default='NA', max_length=64)),
                ('college', models.CharField(default='NA', max_length=64)),
                ('exp', models.CharField(default='NA', max_length=128)),
                ('year', models.CharField(default='NA', max_length=64)),
                ('country', models.CharField(default='NA', max_length=16)),
            ],
        ),
    ]
